version: '3.9'

services:
  utils_openbabel:
    build:
      context: utils_openbabel
      dockerfile: Dockerfile
    image: firesimulations/utils_openbabel:2023.1.2
    container_name: utils_openbabel
    tty: true
    stdin_open: true
    networks:
      - md_utils_net

  utils_docking:
    build:
      context: utils_docking
      dockerfile: Dockerfile
      args:
        - VERSION=2023.1.1
        - IMAGE_VER=lunar-20221216
    image: firesimulations/utils_docking:2023.1.1
    container_name: utils_docking
    tty: true
    stdin_open: true
    networks:
      - md_utils_net

  utils_docking_gpu:
    build:
      context: utils_docking_gpu
      dockerfile: Dockerfile
      args:
        - VERSION=2023.1.1
        - IMAGE_VER=2020.06
    image: firesimulations/utils_docking_gpu:2023.1.1
    container_name: utils_docking_gpu
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - md_utils_net

  # utils_rxdock:
  #   build:
  #     context: utils_rxdock
  #     dockerfile: Dockerfile
  #   image: firesimulations/utils_rxdock:2023.1.1
  #   container_name: utils_rxdock
  #   tty: true
  #   stdin_open: true
  #   networks:
  #     - md_utils_net

  fftw:
    build:
      context: gromacs
      dockerfile: Dockerfile.fftw
      args:
        - UBUNTU_VER=lunar-20221216
        - UBUNTU_BUILD_VER=22.04
        - FFTW_VER=3.3.10
        - GROMACS_VER=2022.4
        - CMAKE_VER=3.25.1
        - GCC_VER=11
        - CUDA_VER=12.0.0
        - OPENMPI_VER=4.1.4
    image: firesimulations/fftw:3.3.10
    container_name: fftw
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - md_utils_net

  # gromacs-sse2:
  #   build:
  #     context: gromacs
  #     dockerfile: Dockerfile.gmx.sse2
  #     args:
  #       - UBUNTU_VER=lunar-20221216
  #       - UBUNTU_BUILD_VER=22.04
  #       - FFTW_VER=3.3.10
  #       - GROMACS_VER=2022.4
  #       - CMAKE_VER=3.25.1
  #       - GCC_VER=11
  #       - CUDA_VER=12.0.0
  #       - OPENMPI_VER=4.1.4
  #   image: firesimulations/gromacs:gmx-2022.4-cuda-12.0.0-sse2
  #   container_name: gromacs-sse2
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ./data:/data
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
  #   networks:
  #     - md_utils_net

  gromacs:
    build:
      context: gromacs
      dockerfile: Dockerfile
      args:
        - UBUNTU_VER=lunar-20221216
        - UBUNTU_BUILD_VER=22.04
        - FFTW_VER=3.3.10
        - GROMACS_VER=2022.4
        - CMAKE_VER=3.25.1
        - GCC_VER=11
        - CUDA_VER=12.0.0
        - OPENMPI_VER=4.1.4
    image: firesimulations/gromacs:gmx-2022.4-cuda-12.0.0
    container_name: gromacs
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - md_utils_net

networks:
  md_utils_net:
    driver: bridge