version: '3.9'

services:
  utils_openbabel:
    build:
      context: utils_openbabel
      dockerfile: Dockerfile
    image: firesimulations/utils_openbabel:2023.1.2
    container_name: utils_openbabel
    tty: true
    stdin_open: true
    networks:
      - md_utils_net

  utils_docking:
    build:
      context: utils_docking
      dockerfile: Dockerfile
    image: firesimulations/utils_docking:2023.1.1
    container_name: utils_docking
    tty: true
    stdin_open: true
    networks:
      - md_utils_net

  utils_docking_gpu:
    build:
      context: utils_docking_gpu
      dockerfile: Dockerfile
    image: firesimulations/utils_docking_gpu:2023.1.1
    container_name: utils_docking_gpu
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - md_utils_net

networks:
  md_utils_net:
    driver: bridge