FROM nvcr.io/hpc/autodock:2020.06

LABEL maintainer="DHN Chandan <biogrids.io@gmail.com>"
LABEL version="2023.1.1"
LABEL github="https://github.com/bio-grids/molecular_dynamics_utils"

# make data work directory
RUN cd / && mkdir -p data
WORKDIR /data