---

name: Build and push openbabel utils

env:
  OPENBABEL_REPO: firesimulations/utils_openbabel
  OPENBABEL_VERSION: 2023.1.2
  OPENBABEL_IMAGE_VER: 3.11-slim-bullseye
  OPENBABEL_VER: 3.1.1

on:
  push:
    branches:
      - 'docker'

jobs:
  check-for-existing-openbabel-image:
    runs-on: ubuntu-latest
    name: Check docker for openbabel tag
    outputs:
      tag-exists: ${{steps.check-docker.outputs.tag-exists}}
    steps:
      - name: Check Docker for Tag
        id: check-docker
        uses: hipcamp/docker-tag-exists@v1
        with:
          image: ${{env.OPENBABEL_REPO}}
          tag: ${{env.OPENBABEL_VERSION}}
  openbabel-docker:
    runs-on: ubuntu-latest
    name: Build and deploy openbabel image
    needs: check-for-existing-openbabel-image
    if: needs.check-for-existing-openbabel-image.outputs.tag-exists != 'true'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:utils_openbabel"
          file: "Dockerfile"
          push: true
          tags: ${{env.OPENBABEL_REPO}}:${{env.OPENBABEL_VERSION}},${{env.OPENBABEL_REPO}}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          VERSION: ${{env.OPENBABEL_VERSION}}
          IMAGE_VER: ${{env.OPENBABEL_IMAGE_VER}}
          OPENBABEL_VER: ${{env.OPENBABEL_VER}}
