---

name: Test tag exists

env:
  fftw_repo: firesimulations/fftw
  gromacs_repo: firesimulations/gromacs
  FFTW_VER: 3.3.10
  GROMACS_VER: 2022.4
  CMAKE_VER: 3.25.1
  GCC_VER: 11
  CUDA_VER: 12.0.0
  OPENMPI_VER: 4.1.4
  UBUNTU_VER: lunar-20221216
  UBUNTU_BUILD_VER: 22.04

on:
  push:
    branches:
      - 'master'

jobs:
  check-for-existing-docker-image:
    runs-on: ubuntu-latest
    name: Check Docker for Matching Tag
    outputs:
      tag-exists: ${{steps.check-docker.outputs.tag-exists}}
    steps:
      - name: Check Docker for Tag
        id: check-docker
        uses: hipcamp/docker-tag-exists@v1
        with:
          image: firesimulations/gromacs
          tag: gmx-2022.4-cuda-12.0.0
  build-and-deploy-docker-image:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    needs: check-for-existing-docker-image
    if: needs.check-for-existing-docker-image.outputs.tag-exists != 'true'
    steps:
      - run: echo "Build and Deploy Docker Image"
